language: python
python:
- 3.5
sudo: false
env:
- TOXENV=py27-django18
- TOXENV=py27-django19
- TOXENV=py34-django18
- TOXENV=py34-django19
- TOXENV=py35-django19
- TOXENV=coverage
install:
- pip install -q tox
script:
- tox
deploy:
  provider: pypi
  user: MrYoda
  password:
    secure: qxuOnh/JBTDDuNJr8T4tpxoO7ThEM7ofkXkuuUfI/YJfoyz7cSK1zJpDO7eKOgxiChZYQqOF20CVTCbkZHICvRSmmOuSr9BPyS2bkCUx9/tVZ49oC1dFk/VNDnIg/Vw7ghzijnIErAZ25dBz9Blmuy16UYhSoGYZ0zGXqIRB5TX/J1H8+cBKdzbiag7RS29OwpJtpsLZkoOmhn+1mcJb6TXV1SmO7IPwsgTW8mZefESKFhj0ZuhPMX5bBssdlI5SEYPnsPdQrB6bJoyRanfQcD0HIZotjaMH30OMlFFAGVilqFrwp1H5zGV2HDwln+0s0eODvalys4GEa7TP5JEl5cglPgkatTmqtxs5WSfEV8befUhnWMsesbLJHJt1LL2Pu1Mcp1aeY2Os28NdUB2ZXzwzQs6lvxZxDowHie0HK3wl7Lu6QQT3dpvFtTTScF3CGD+vsSeVgAeVDuytCYl60KFUCKkzzj+jnEAHFnzz9yp8sXSTqgKrhS81/mkZDEWtkGMlqtPAApzPSM4FsCX5YbI6JMAS2qTj5WOjzXp3oNssvR4yyOz9MKYpQJJBi9wz+WMzEXSkX+EVLi+OX+INo8ssQBUHikJn66aYf3o/fT4MfO5EArEbtpmQuFEVOkHZUzvH9+YBjaMoT6KOQP6NXWoWNl+I2VTFT/YSc5osgo8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: DirectlineDev/django-robokassa-merchant
